=== vyshnavikatikala/EY_Intern_Training/day23invoiceapp/invoice.dtd
<!ELEMENT invoice (customer+,items+)>
<!ELEMENT customer (customerno,customername,customeraddress,customeremail,customerphone,invoiceno)>
<!ELEMENT customerno (#PCDATA)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT customeraddress (#PCDATA)>
<!ELEMENT customeremail (#PCDATA)>
<!ELEMENT customerphone (#PCDATA)> 
<!ELEMENT invoiceno (#PCDATA)> 
<!ELEMENT items (item+)>
<!ELEMENT item (itemno,itemdescription,itemprice,itemqty,itemunit,itemtotal)>
<!ELEMENT itemno (#PCDATA)>
<!ELEMENT itemdescription (#PCDATA)>
<!ELEMENT itemprice (#PCDATA)>
<!ELEMENT itemqty (#PCDATA)>
<!ELEMENT itemunit (#PCDATA)> 
<!ELEMENT itemtotal (#PCDATA)>

=== vyshnavikatikala/EY_Intern_Training/day23invoiceapp/invoice.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd"><invoice><customer><customerno>4</customerno><customername>Ranjith</customername><customeraddress>Banglore</customeraddress><customeremail>ranjithsrinivasan2@gmail.com</customeremail><customerphone>9878456512</customerphone><invoiceno>117</invoiceno></customer><items><item><itemno>1001</itemno><itemdescription>Dairy Milk</itemdescription><itemprice>50</itemprice><itemqty>1</itemqty><itemunit>1 pkt</itemunit><itemtotal>50</itemtotal></item><item><itemno>1002</itemno><itemdescription>Pringles Chips</itemdescription><itemprice>100</itemprice><itemqty>2</itemqty><itemunit>1 pkt</itemunit><itemtotal>200</itemtotal></item></items></invoice>
